### ISSUE TITLE
Finalizing Dawg 2.0

### ISSUE THREAD

**Issue by reedacartwright** [CartwrightLab/dawg#65]
A possible list of tasks that need to be completed to polish up the Dawg 2.0 code base in preparation for a paper.

- [ ] #68
  - [ ] Update code to C++17 standards
- [ ] #72
  - [ ] Replace trick file format with Yaml. Use `rapidyaml` library for parsing.
  - [ ] Support linking libdawg with R and Python
- [ ] #66
- [ ] #69
- [ ] Use CLI11 for program options.
- [ ] #70
- [ ] #71
- [ ] Create testing framework, both unit tests and functional tests.
- [ ] Auto-format the code.
- [ ] Lint the code.
- [ ] #67
- [ ] Optimize code

**Comment by reedacartwright** [comment]
Here's the beginnings of a proposal for replacing trick with yaml. At the top level, there are three+ sections. `parts` defines partitions of the root sequence and the root sequence itself. `rules` defines evolutionary models. `regions` defines sections of tree space with known topology and branch length, tied to a partition, and has an evolutionary model.

```yaml
reps: 100 # can be overridden on the command line
seed: [1,2,3] # can be overridden on the command line

parts:
- name: exon_1
  length: 1000 # ignored because seq is specified
  seq: "ACGT"
  type: DNA

rules:
-
  name: default
  subst:
    model: k2p
    alpha: 1
    freqs: [0,2,3,4]
  ins:
    rate: 0.01
    model: powerlaw
    alpha: 1.5
    max_len: 100
  del:
    rate: 0.01
    type: powerlaw
    alpha: 1.5
    max_len: 100

regions:
-
  tree: "(A:0.1,B:0.1).R;"
  rule: default
  part: exon_1
```
